import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex items-center justify-between p-4 border-b border-zinc-200 dark:border-zinc-700 mb-8">
          <div className="mr-4">LOGO - HR Portal</div>
          <ul className="flex gap-4">
            <li><a href="/profile">Profile</a></li>
            <li><a href="/leave-requests">Leave Requests</a></li>
            <li><a href="/">Logout</a></li>
          </ul>
        </div>
        <div className="font-sansk">
          <main className="p-4">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
