import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="container flex flex-col md:flex-row items-center justify-between mx-auto">
          <div className="mb-4 md:mb-0 mr-0 md:mr-4">
            <Image src="/hr-portal-logo1.png" alt="HR Portal Logo" width={75} height={75} />
          </div>
          <ul className="flex flex-col md:flex-row gap-4 text-center md:text-left">
            <li><a href="/hr-dashboard">Dashboard</a></li>
            <li><a href="/profile">Profile</a></li>
            <li><a href="/leave-requests">Leave Requests</a></li>
            <li><a href="/">Logout</a></li>
          </ul>
        </div>
        <div className="font-sans container">
          <main className="p-4">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
